### ISSUE TITLE
[enhancement] make it work with kde (konsole)

### ISSUE THREAD

**Issue by plop28** [rizitis/Slackware-Commander#1]
Hi, installation works well but I can't use it with KDE.
Many workaround can be done, but i choose to replace hard coded xfce4-terminal to konsole :

> sed -i 's/xfce4-terminal -H -x/konsole --hold -e/g' /usr/local/bin/Slackware-Commander.sh
> sed -i 's/xfce4-terminal -x/konsole -e/g' /usr/local/bin/Slackware-Commander.sh
> sed -i 's/xfce4-terminal/konsole/g' /usr/local/bin/Slackware-Commander.sh 

thanks for the work done.

**Comment by rizitis** [comment]
You are a slacker... you know how to fix it for your needs ;-)

**Comment by rizitis** [comment]
kosnole from now is the default.
